INSERT INTO `sis_modulos` (`id`, `modulo_id`, `nome`, `ordem_menu`, `tela`, `caminho`, `acao_menu`, `menu_escondido`) VALUES
(1, 0, 'Administrativo', 1, 'index.php', 'modulos/administrativo/clientes/', 'expande', ''),
(3, 0, 'Estoque', 20, 'unidades.php', 'modulos/estoque/almoxarifado', 'expande', ''),
(4, 0, 'Monitoramento de Obra 0%', 30, '', '', 'expande', ''),
(5, 0, 'Financeiro', 40, 'caixa.php', 'modulos/financeiro/caixa/', 'expande', ''),
(6, 0, 'Sistema', 900, '', '', 'expande', ''),
(8, 0, 'Imobiliária Construtora', 50, 'corretor.php', 'modulos/corretor/corretor/', 'expande', ''),
(13, 1, 'Usuários', 70, 'index.php', 'modulos/administrativo/usuarios/', 'abre', '0'),
(14, 1, 'Tipos de Usuarios', 80, 'index.php', 'modulos/administrativo/tipos_usuarios/', 'abre', '0'),
(15, 1, 'Clientes', 10, 'index.php', 'modulos/administrativo/clientes/', 'abre', '0'),
(16, 1, 'Fornecedores', 20, 'index.php', 'modulos/administrativo/fornecedores/', 'abre', '0'),
(17, 8, 'Empreendimentos', 30, 'empreendimentos_admin.php', 'modulos/administrativo/empreendimentos/', 'abre', ''),
(18, 8, 'Obras', 40, 'index.php', 'modulos/administrativo/obras/', 'abre', ''),
(19, 8, 'Planejamentos / Orçamentos', 60, 'index.php', 'modulos/administrativo/planejamentos', 'abre', ''),
(20, 8, 'Contrato Imobiliário', 50, 'contratos_admin.php', 'modulos/administrativo/contratos_admin/', 'abre', ''),
(37, 8, 'Cadastro de Cliente', 10, 'index.php', 'modulos/corretor/cadastro_clientes/', 'abre', '0'),
(38, 8, 'Vendas', 40, 'index.php', 'modulos/corretor/vendas/', 'abre', '0'),
(39, 8, 'Empreendimentos', 20, 'empreendimentos_corretor.php', 'modulos/corretor/empreendimentos', 'abre', '0'),
(41, 13, 'Histórico', 0, 'historico.php', 'modulos/administrativo/usuarios/', 'interno', '0'),
(42, 3, 'Inventários', 50, 'index_inventarios.php', 'modulos/estoque/inventarios', 'abre', ''),
(45, 550, 'Cotação', 25, 'necessidade_cotacao.php', 'modulos/cozinha/cotacao/', 'abre', ''),
(47, 4, 'Acompanhamento', 0, '', '', 'expande', '0'),
(48, 4, 'Autorização de Pagamento', 0, '', '', '', '0'),
(49, 5, 'Contas', 10, 'contas.php', 'modulos/financeiro/contas/', 'abre', '0'),
(50, 5, 'Centro de Custos', 20, 'centro_de_custos.php', 'modulos/financeiro/centro_de_custos/', 'abre', '0'),
(51, 5, 'Plano de Contas', 30, 'plano_de_contas.php', 'modulos/financeiro/plano_de_contas/', 'abre', '0'),
(52, 5, 'Contas a Pagar', 50, 'contas_a_pagar.php', 'modulos/financeiro/contas_a_pagar/', 'abre', '1'),
(53, 5, 'Contas a Receber', 40, 'contas_a_receber.php', 'modulos/financeiro/contas_a_receber/', 'abre', '1'),
(54, 5, 'Caixa', 60, 'caixa.php', 'modulos/financeiro/caixa/', 'abre', '1'),
(58, 17, 'Negociações', 0, 'negociacao.php', 'modulos/administrativo/empreendimentos/negociacao/', 'interno', '0'),
(60, 17, 'Disponibilidades', 0, 'disponibilidade.php', 'modulos/administrativo/empreendimentos/disponibilidades/', 'interno', '0'),
(61, 60, 'Reservas', 0, 'index.php', 'modulos/administrativo/empreendimentos/disponibilidades/reservas/', 'interno', '0'),
(62, 17, 'Planejamentos / Orçamentos', 0, 'index.php', 'modulos/administrativo/planejamentos', 'interno', '0'),
(65, 17, 'Tipos de Disponibilidades', 0, 'disponibilidade_tipo.php', 'modulos/administrativo/empreendimentos/disponibilidade_tipo/', 'interno', '0'),
(66, 39, 'Disponibilidades', 0, 'disponibilidade.php', 'modulos/corretor/empreendimentos/disponibilidades/', 'interno', '0'),
(67, 8, 'Interesses', 30, 'index.php', 'modulos/corretor/interesses/', 'abre', '0'),
(68, 37, 'Arquivos', 0, 'index.php', 'modulos/corretor/cadastro_clientes/arquivos/', 'interno', '0'),
(69, 15, 'Arquivos', 0, 'index.php', 'modulos/administrativo/clientes/arquivos/', 'interno', '0'),
(70, 20, 'Detalhes Contrato', 0, 'exibicao_contrato.php', 'modulos/administrativo/contratos_admin', 'abre', '0'),
(78, 71, 'Inventários', 1, 'inventarios.php', 'modulos/estoque/produtos/', 'interno', '0'),
(79, 5, 'Relatorios', 100, '', '', 'expande', '0'),
(80, 5, 'Fluxo de Caixa diário', 65, 'fluxo_caixa.php', 'modulos/financeiro/fluxo_caixa/', 'abre', '1'),
(82, 79, 'Anual', 0, 'demonstrativo_anual.php', 'modulos/financeiro/relatorios/demonstrativo_anual/', 'abre', '0'),
(83, 50, 'Planejamento', 0, 'planejamento_centro_de_custos.php', 'modulos/financeiro/centro_de_custos/', 'abre', '0'),
(84, 51, 'Planejamento', 0, 'planejamento_plano_de_conta.php', 'modulos/financeiro/plano_de_contas/', 'abre', '0'),
(85, 79, 'Busca por Período', 0, 'busca.php', 'modulos/financeiro/relatorios/busca/', 'abre', '0'),
(86, 5, 'Contas Fixas', 67, 'contas_fixas.php', 'modulos/financeiro/contas_fixas/', 'abre', '0'),
(87, 5, 'Financiamentos ', 68, 'contratos.php', 'modulos/financeiro/contratos/', 'abre', '0'),
(88, 5, 'Cheques', 69, 'cheques.php', 'modulos/financeiro/cheques/', 'abre', '0'),
(89, 0, 'Controle de Atividades', 60, 'colaborador.php', 'modulos/projetos/atividades/colaborador', 'expande', ''),
(90, 526, 'Tipo de Atividade', 5, 'tipo_atividades.php', 'modulos/projetos/tipo_atividades/', 'abre', '0'),
(91, 526, 'Projetos', 0, 'projetos.php', 'modulos/projetos/', 'abre', ''),
(92, 89, 'Administrar Atividades', 30, 'atividades.php', 'modulos/projetos/atividades', 'abre', '1'),
(93, 0, 'Departamento Pessoal', 60, 'empresa.php', 'modulos/rh/empresa', 'expande', ''),
(95, 98, 'Relatório Funcionários', 1, 'relatorio_funcionario.php', 'modulos/projetos/relatorios/', 'abre', '0'),
(96, 89, 'Minhas Atividades', 10, 'colaborador.php', 'modulos/projetos/atividades/colaborador', 'abre', '1'),
(97, 98, 'Relatório Projetos', 10, 'relatorio_projeto.php', 'modulos/projetos/relatorios/', 'abre', '0'),
(98, 89, 'Relatórios', 40, '', '', 'expande', '0'),
(99, 0, 'Cozinha', 60, 'grupo_cardapio.php', 'modulos/cozinha/grupo_cardapio', 'expande', ''),
(101, 99, 'Cardapio', 20, 'cardapio.php', 'modulos/cozinha/cardapio/', 'abre', '0'),
(102, 99, 'Cadastro de Ficha Técnica', 2, 'ficha_tecnica.php', 'modulos/cozinha/ficha_tecnica/', 'abre', '0'),
(103, 548, 'Almoxarifado', 1, 'unidades.php', 'modulos/estoque/almoxarifado/', 'abre', ''),
(104, 99, 'Contrato', 10, 'contrato.php', 'modulos/cozinha/contrato/', 'abre', '0'),
(107, 548, 'Cadastro de Produtos', 3, 'index.php', 'modulos/estoque/produtos/', 'abre', ''),
(108, 548, 'Produtos por Fornecedor', 20, 'produtos_fornecedor.php', 'modulos/estoque/produtos_fornecedor/', 'abre', ''),
(109, 553, 'Beneficiamento', 70, 'beneficiamento.php', 'modulos/estoque/beneficiamento/', 'abre', ''),
(110, 550, 'Comprar', 30, 'compras.php', 'modulos/estoque/compras/', 'abre', ''),
(111, 99, 'Grupo Fichas Técnicas', 1, 'grupo_cardapio.php', 'modulos/cozinha/grupo_cardapio', 'abre', '0'),
(112, 99, 'Quebra', 80, 'quebra.php', 'modulos/cozinha/quebra', 'abre', '0'),
(113, 99, 'Controle de Consumo', 60, 'controle_consumo.php', 'modulos/cozinha/controle_consumo', 'abre', '0'),
(115, 99, 'Remessa Unidade', 40, 'remessa.php', 'modulos/cozinha/remessa_unidade', 'abre', '0'),
(116, 99, 'Faturamento', 70, 'faturamento.php', 'modulos/cozinha/faturamento', 'abre', '0'),
(117, 99, 'Necessidades Central', 30, 'necessidade_central.php', 'modulos/cozinha/necessidade_central', 'abre', '0'),
(118, 45, 'Cotação Produto', 0, 'comparacao.php', 'modulos/cozinha/cotacao', 'interno', '0'),
(119, 45, 'Cotação no Fornecedor', 1, 'cotacao.php', 'modulos/cozinha/cotacao', 'interno', '0'),
(120, 115, 'Remessa Unidade', 65, 'envio.php', 'modulos/cozinha/remessa_unidade', 'interno', '0'),
(121, 548, 'Grupos de Produtos', 2, 'grupos.php', 'modulos/estoque/produtos_grupos/', 'abre', ''),
(122, 0, 'Eleitoral', 120, 'eleitores.php', 'modulos/eleitoral/eleitores', 'expande', ''),
(123, 122, 'Eleitores', 20, 'eleitores.php', 'modulos/eleitoral/eleitores', 'abre', '0'),
(124, 110, 'Novo Pedido', 0, 'novo_pedido.php', 'modulos/estoque/compras/', 'interno', '0'),
(128, 122, 'Pedidos', 50, '', 'modulos/eleitoral/pedidos/', 'expande', '0'),
(132, 128, 'Pedidos', 128, 'pedidos.php', 'modulos/eleitoral/pedidos/', 'abre', '0'),
(133, 122, 'Cadastros', 70, '', 'modulos/eleitoral/cadastros/', 'expande', '0'),
(135, 133, 'Profissoes', 133, 'profissoes.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(136, 133, 'Zonas', 134, 'zona.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(137, 133, 'Vinculos', 135, 'vinculos.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(138, 133, 'Setores', 136, 'setor.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(139, 133, 'Regioes', 137, 'regioes.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(140, 133, 'Partidos', 138, 'partidos.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(141, 122, 'Politico', 30, 'vereador.php', 'modulos/eleitoral/politicos', 'abre', '0'),
(142, 133, 'Coligacoes', 140, 'coligacao.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(143, 122, 'Colaboradores', 40, 'colaborador.php', 'modulos/eleitoral/colaborador', 'abre', '0'),
(144, 133, 'Grupos Sociais', 124, 'grupo_sociais.php', 'modulos/eleitoral/sociais', 'abre', '0'),
(145, 133, 'Funcoes', 141, 'funcoes.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(146, 122, 'Relatórios', 90, '', '', 'expande', '0'),
(147, 146, 'Candidato', 1, 'relatorio.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(148, 122, 'Resumo', 10, 'index.php', 'modulos/eleitoral/resumo_campanha/', 'abre', '0'),
(149, 133, 'Religioes', 143, 'religioes.php', 'modulos/eleitoral/cadastros', 'abre', '0'),
(151, 122, 'Envio de SMS', 60, '', '', 'expande', '0'),
(155, 151, 'Enviar SMS', 10, 'EleitoralEnviaSMS.php', 'modulos/sysms/views', 'abre', '0'),
(156, 146, 'Bens Imóveis', 0, 'bens.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(157, 146, 'Carros', 1, 'bens_carros.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(158, 146, 'Lancha', 2, 'bens_lancha.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(159, 0, 'Vekttor', 130, 'index.php', 'modulos/vekttor/clientes/', 'expande', ''),
(160, 159, 'Clientes', 120, 'index.php', 'modulos/vekttor/clientes/', 'abre', '1'),
(161, 146, 'Motos', 50, 'bens_motos.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(162, 146, 'Barcos', 90, 'bens_barcos.php', 'modulos/eleitoral/relatorios/', 'abre', '0'),
(164, 8, 'Corretor', 0, 'corretor.php', 'modulos/corretor/corretor', 'abre', '0'),
(165, 1, 'Dono Cliente', 10, 'dono_cliente.php', 'modulos/administrativo/donoCliente', 'abre', '0'),
(166, 38, 'Detalhes do Contrato', 0, 'exibicao_contrato.php', 'modulos/corretor/vendas', 'abre', '0'),
(167, 8, 'Relatórios', 60, '', 'modulos/corretor/relatorios', 'expande', '0'),
(169, 167, 'Vendas Corretor', 10, 'vendas_por_corretor.php', 'modulos/corretor/relatorios/corretor_venda', 'abre', '0'),
(170, 8, 'Contratos', 50, 'contratos.php', 'modulos/corretor/contratos/', 'abre', '0'),
(171, 170, 'Detalhes Contrato', 1, 'detalhes_contrato.php', 'modulos/corretor/contratos/', 'interno', '0'),
(172, 8, 'Negociações Restritas', 120, 'negociacoes_restritas.php', 'modulos/administrativo/negociacoes_restritas/', 'abre', ''),
(173, 167, 'Cliente Ramo Atividade', 90, 'index.php', 'modulos/corretor/relatorios/cliente_ramo_atividade', 'abre', '0'),
(174, 167, 'Cliente por Bairro', 60, 'index.php', 'modulos/corretor/relatorios/cliente_por_bairro', 'abre', '0'),
(175, 167, 'Cliente por Corretor', 70, 'index.php', 'modulos/corretor/relatorios/cliente_vendedor', 'abre', '0'),
(176, 167, 'Corretor por Imobiliária', 30, 'index.php', 'modulos/corretor/relatorios/corretor_por_imobiliaria', 'abre', '0'),
(177, 167, 'Interesses', 0, 'index.php', 'modulos/corretor/relatorios/interesses', 'abre', '0'),
(178, 167, 'Vendas Imobiliária', 0, 'imobiliaria_venda.php', 'modulos/corretor/relatorios/imobiliaria_venda', 'abre', '0'),
(179, 167, 'Total Venda Imobiliária', 0, 'total_imobiliaria.php', 'modulos/corretor/relatorios/imobiliaria_venda', 'interno', '0'),
(180, 167, 'Total Venda Corretor', 0, 'total_venda.php', 'modulos/corretor/relatorios/corretor_venda', 'interno', '0'),
(181, 527, 'Revenda/Franquia', 0, 'revenda_franquia.php', 'modulos/vekttor/revenda_franquia', 'abre', ''),
(182, 159, 'Item no Menu', 0, 'item_menu.php', 'modulos/vekttor/item_menu', 'abre', '1'),
(183, 4, 'teste', 0, 'teste.php', 'modulos/tete/teste', 'expande', '0'),
(184, 4, 'teste', 0, 'teste.php', 'modulos/tete/teste', 'expande', '0'),
(191, 551, 'Orçamento Vendedor', 40, 'vendas.php', 'modulos/estoque/vendas', 'abre', ''),
(192, 552, 'Transferir de Mercadoria', 50, 'transferencia.php', 'modulos/estoque/transferencia', 'abre', ''),
(193, 192, 'Itens da Transferencia', 0, 'transferencia_item.php', 'modulos/estoque/transferencia', 'abre', '0'),
(194, 42, 'Detalhes Inventário', 1, 'detalhe_inventario.php', 'modulos/estoque/inventarios/detalhe_inventario/', 'interno', '0'),
(195, 552, 'Recebimento de Transferência', 60, 'recebimento_transferencia.php', 'modulos/estoque/transferencia_recebimento', 'abre', ''),
(196, 195, 'Itens da Transferência', 0, 'recebimento_item.php', 'modulos/estoque/transferencia_recebimento', 'abre', '0'),
(197, 550, 'Recebimento de Compra', 35, 'recebimento.php', 'modulos/estoque/compras_recebimento/', 'abre', ''),
(198, 197, 'Recebimento', 0, 'compras_recebimento.php', 'modulos/estoque/compras_recebimento/', 'abre', '0'),
(199, 98, 'Colaborador por Periodo', 0, 'colaborador_por_periodo.php', 'modulos/projetos/relatorios', 'abre', ''),
(200, 553, 'Beneficiamento Recebimento', 80, 'beneficiamento_recebimento.php', 'modulos/estoque/beneficiamento_recebimento', 'abre', ''),
(201, 191, 'Nova Venda', 0, 'nova_venda.php', 'modulos/estoque/vendas/', 'abre', '0'),
(202, 112, 'Item Contrato', 0, 'item_quebra.php', 'modulos/cozinha/quebra', 'abre', '0'),
(203, 99, 'Necessidade Unidade', 35, 'necessidade_unidade_2.php', 'modulos/cozinha/necessidade_unidade', 'abre', '0'),
(204, 0, 'Escolar', 50, '', '', 'expande', '0'),
(206, 224, 'Unidades', 10, 'unidades.php', 'modulos/escolar/unidades/', 'abre', '0'),
(208, 224, 'Periodos Letivos', 20, 'periodos.php', 'modulos/escolar/periodos/', 'abre', '0'),
(210, 224, 'Curso', 30, 'cursos.php', 'modulos/escolar/cursos/', 'abre', '0'),
(211, 224, 'Turma', 60, 'salas.php', 'modulos/escolar/salas', 'abre', '0'),
(212, 224, 'Horarios / Turno', 50, 'horarios.php', 'modulos/escolar/horarios/', 'abre', '0'),
(215, 204, 'Alunos', 90, 'index.php', 'modulos/escolar/alunos_inscritos', 'abre', '0'),
(216, 204, 'Exportação', 157, 'exportacao.php', 'modulos/escolar/exportacao/', 'abre', '0'),
(217, 204, 'Matriculas', 70, 'matriculas.php', 'modulos/escolar/matriculas/', 'abre', '0'),
(218, 204, 'Retorno do banco bb muraki', 158, 'retorno.php', 'modulos/financeiro/retorno_banco/', 'abre', ''),
(219, 224, 'Bolsistas', 120, 'bolsistas.php', 'modulos/escolar/bolsistas/', 'abre', '0'),
(220, 224, 'Inadimplentes', 130, 'Inadimplentes.php', 'modulos/escolar/Inadimplentes/', 'abre', '0'),
(221, 204, 'Aniversariantes', 160, 'relatorio_aniversariante.php', 'modulos/escolar/relatorios', 'abre', '0'),
(222, 204, 'Responsaveis', 80, 'responsavel.php', 'modulos/escolar/responsavel/', 'abre', '0'),
(223, 221, 'Relatório Sistético', 1, 'relatrorio_sistentico.php', 'modulos/escolar/relatorios/', 'interno', '0'),
(224, 204, 'Cadastro', 155, '', '', 'expande', '0'),
(225, 203, 'Nova Necessidade', 0, 'necessidade_unidade.php', 'modulos/cozinha/necessidade_unidade', 'interno', '0'),
(226, 204, 'Visão Geral', 0, 'relatorio_sintetico.php', 'modulos/escolar/relatorios', 'abre', '0'),
(227, 211, 'Alunos da Sala', 170, 'salas_alunos.php', 'modulos/escolar/salas/', 'interno', '0'),
(228, 204, 'Relatório de Alergias', 180, 'alergia.php', 'modulos/escolar/alergias/', 'abre', '0'),
(229, 228, 'Alunos Com Alergias', 190, 'alunos_alergias.php', 'modulos/escolar/alergias/', 'interno', '0'),
(230, 226, 'Alunos', 1, 'alunos_lista.php', 'modulos/escolar/relatorios', 'interno', '0'),
(232, 224, 'Professor', 62, 'professor.php', 'modulos/escolar/professor', 'abre', '0'),
(234, 224, 'Materia', 35, 'materia.php', 'modulos/escolar/materia', 'abre', '0'),
(243, 242, 'Turmas', 0, 'professor_turma.php', 'modulos/escolar/area_professor/turma', 'interno', '0'),
(244, 204, 'Área do Professor', 100, 'area_professor.php', 'modulos/escolar/area_professor', 'abre', '0'),
(256, 244, 'Lista Avaliação', 0, 'lista_avaliacao.php', 'modulos/escolar/area_professor/avaliacao', 'interno', '0'),
(258, 256, 'Nota Avaliação', 0, 'nota_aluno_avaliacao.php', 'modulos/escolar/area_professor/avaliacao', 'interno', '0'),
(259, 244, 'Lista Aula', 0, 'lista_chamada.php', 'modulos/escolar/area_professor/aula', 'interno', '0'),
(260, 259, 'Chamada', 0, 'chamada_aluno_aula.php', 'modulos/escolar/area_professor/aula', 'interno', '0'),
(261, 224, 'Professor por Turma', 63, 'professor_sala.php', 'modulos/escolar/professor_sala', 'abre', '0'),
(262, 244, 'Média', 0, 'lista_alunos.php', 'modulos/escolar/area_professor/media', 'interno', '0'),
(263, 218, 'Matriculas do Arquivo', 0, 'matriculas.php', 'modulos/financeiro/retorno_banco/', 'interno', '0'),
(264, 224, 'Periodo de Avaliação', 61, 'periodicidade.php', 'modulos/escolar/periodicidade', 'abre', '0'),
(266, 262, 'Média Final', 0, 'media_final.php', 'modulos/escolar/area_professor/media', 'interno', '0'),
(267, 259, 'Faltas', 0, 'falta_materia.php', 'modulos/escolar/area_professor/faltas', 'interno', '0'),
(268, 167, 'Comissão Corretor', 80, 'comissao_corretor.php', 'modulos/corretor/relatorios/comissao_corretor', 'abre', '0'),
(269, 167, 'Comissão Imobiliária', 35, 'comissao_imobiliaria.php', 'modulos/corretor/relatorios/comissao_imobiliaria', 'abre', '0'),
(270, 244, 'Avaliação Recuperação', 0, 'lista_avaliacao_recuperacao.php', 'modulos/escolar/area_professor/avaliacao', 'interno', '0'),
(271, 204, 'Área do Aluno', 105, 'area_aluno.php', 'modulos/escolar/area_aluno', 'expande', '0'),
(272, 244, 'Lista Alunos Recuperação', 0, 'lista_alunos_recuperacao.php', 'modulos/escolar/area_professor/media', 'interno', '0'),
(273, 244, 'Nota Aluno Recuperação', 0, 'nota_aluno_recuperacao.php', 'modulos/escolar/area_professor/avaliacao', 'interno', '0'),
(274, 244, 'Visualizar Nota Recuperação', 0, 'visualizar_notas_recuperacao.php', 'modulos/escolar/area_professor/avaliacao', 'interno', '0'),
(275, 0, 'Ordem Serviço', 18, 'odem_servico.php', 'modulos/ordem_servico/ordem_servico', 'expande', ''),
(276, 275, 'O.S Cadastro', 10, 'odem_servico.php', 'modulos/ordem_servico/ordem_servico', 'abre', '0'),
(277, 277, 'Serviços', 0, 'servicos.php', 'modulos/ordem_servico/servicos', 'abre', '0'),
(279, 432, 'Cargos e Salários ', 40, 'cargo_salario.php', 'modulos/rh/cargos_salarios', 'abre', '0'),
(280, 306, 'Produtos Vendidos', 0, 'produtos.php', 'modulos/ordem_servico/relatorios', 'abre', '0'),
(281, 319, 'Visitas', 0, 'visita.php', 'modulos/ordem_servico/agenda_visita', 'abre', '0'),
(282, 285, 'Forum', 0, 'pagina_principal_forum.php', 'modulos/escolar/area_aluno/forum', 'interno', '0'),
(283, 479, ' Notas', 1, 'notas.php', 'modulos/escolar2/area_aluno/notas', 'abre', '0'),
(284, 271, 'Faltas', 2, 'faltas.php', 'modulos/escolar/area_aluno/faltas', 'abre', '0'),
(285, 271, 'Aulas', 3, 'materias.php', 'modulos/escolar/area_aluno/aulas/', 'abre', '0'),
(286, 259, 'Upload Arquivo', 0, 'lista_arquivo.php', 'modulos/escolar2/area_professor/aula/arquivo', 'interno', '0'),
(287, 285, 'Aulas', 1, 'aulas.php', 'modulos/escolar/area_aluno/aulas/', 'interno', '0'),
(288, 287, 'Aula', 0, 'aula.php', 'modulos/escolar/area_aluno/aulas/', 'interno', '0'),
(289, 288, 'Mensagens Professor', 0, 'mesagem_para_professor.php', 'modulos/escolar/area_aluno/aulas/', 'interno', '0'),
(291, 244, 'Forum', 0, 'forum_pergunta.php', 'modulos/escolar/area_professor/forum', 'interno', '0'),
(292, 291, 'Todas Perguntas', 0, 'todas_perguntas_forum.php', 'modulos/escolar/area_professor/forum', 'interno', '0'),
(293, 271, 'Tradutor', 25, 'tradutor.php', 'modulos/escolar/area_aluno/tradutor', 'abre', '0'),
(294, 271, 'Mensagens Privadas', 30, 'mensagens_privadas.php', 'modulos/escolar/area_aluno/mensagens', 'abre', '0'),
(296, 291, 'Todas Perguntas', 0, 'todas_perguntas_inicio.php', 'modulos/escolar/area_professor/forum', 'interno', '0'),
(297, 244, 'Mensagens Privadas', 10, 'mensagens.php', 'modulos/escolar/area_professor/mensagens/', 'interno', '0'),
(298, 294, 'Mensagens', 35, 'todas_mensagens.php', 'modulos/escolar/area_aluno/mensagens', 'interno', '0'),
(299, 297, 'Mensagens', 15, 'todas_mensagens.php', 'modulos/escolar/area_professor/mensagens/', 'interno', '0'),
(300, 285, 'Lista Discussões', 0, 'lista_pergunta_aula.php', 'modulos/escolar/area_aluno/forum', 'interno', '0'),
(301, 306, 'Serviços Vendidos', 0, 'servicos_vendidos.php', 'modulos/ordem_servico/relatorios/servicos', 'abre', '0'),
(302, 306, 'Comissão Funcionários', 0, 'comissao_funcionario.php', 'modulos/ordem_servico/relatorios', 'abre', '0'),
(303, 0, 'Aluguel', 14, 'index.php', 'modulos/aluguel/locacao_devolucao', 'expande', ''),
(304, 303, 'Cadastro de Equipamentos', 30, 'equipamento.php', 'modulos/aluguel/equipamento', 'abre', '0'),
(305, 303, 'Locação / Devolução', 10, 'index.php', 'modulos/aluguel/locacao_devolucao', 'abre', '0'),
(306, 275, 'Relatórios', 30, '', '', 'expande', '0'),
(307, 306, 'Receitas X Despesas', 0, 'receitas.php', 'modulos/ordem_servico/relatorios/receitas', 'abre', '0'),
(308, 303, 'Modelo de Contrato', 40, 'contrato.php', 'modulos/aluguel/contrato', 'abre', '0'),
(309, 275, 'Configuração da OS', 19, 'configuracao_os.php', 'modulos/ordem_servico/configuracao', 'abre', '0'),
(310, 454, 'Cobrança', 45, '', '', 'expande', '0'),
(311, 310, 'Gerar Mensalidades', 0, 'mensalidades_escolar.php', 'modulos/cobranca/mensalidades_escolar', 'abre', '0'),
(312, 310, 'Impressão Por aluno', 1, 'impressao_boletos.php', 'modulos/cobranca/mensalidades_escolar/mensalidade_escolar_impressao/', 'abre', '0'),
(314, 303, 'Relatorios', 50, '', '', 'expande', '0'),
(315, 314, 'Disponibilidade Equipamento', 0, 'disponibilidade.php', 'modulos/aluguel/relatorios/disponibilidade', 'abre', '0'),
(316, 310, 'Impressão Massa', 1, 'impressao_boletos_massa.php', 'modulos/cobranca/mensalidades_escolar/mensalidade_escolar_impressao_massa/', 'abre', '0'),
(317, 303, 'Orçamento', 20, 'orcamento.php', 'modulos/aluguel/orcamento', 'abre', '0'),
(318, 314, 'Receitas VS Despesas', 0, 'receitas.php', 'modulos/aluguel/relatorios/receitas', 'abre', '0'),
(319, 275, 'Cadastros', 20, '', '', 'expande', '0'),
(320, 319, 'Serviços', 0, 'servicos.php', 'modulos/ordem_servico/servicos', 'abre', '0'),
(321, 319, 'Atendimento', 0, 'atendimento.php', 'modulos/ordem_servico/atendimento', 'abre', '0'),
(323, 204, 'Relatório de Notas e Faltas', 200, 'notas_faltas.php', 'modulos/escolar/notas_faltas', 'abre', '0'),
(324, 204, 'Aulas Online', 102, 'aulas_online.php', 'modulos/escolar/aulas_online_cadastro/', 'abre', '0'),
(325, 324, 'Aulas do Módulo', 0, 'lista_aulas_modulo.php', 'modulos/escolar/aulas_online_cadastro/aulas_online_cadastradas/', 'interno', '0'),
(326, 325, 'Arquivos da aula', 5, 'arquivos_aula_online.php', 'modulos/escolar/aulas_online_cadastro/aulas_online_cadastradas/arquivos_aula_online/', 'abre', '0'),
(327, 271, 'Aulas Online', 5, 'materias_online.php', 'modulos/escolar/area_aluno/aulas_online/', 'abre', '0'),
(328, 327, 'Aulas da Matéria', 1, 'aula_online_lista.php', 'modulos/escolar/area_aluno/aulas_online/aulas_online_lista/', 'interno', '0'),
(329, 303, 'Configuração do Aluguel', 60, 'configuracao_aluguel.php', 'modulos/aluguel/configuracao', 'abre', '0'),
(330, 328, 'Ver Aula', 5, 'ver_aula_online.php', 'modulos/escolar/area_aluno/aulas_online/ver_aula_online', 'interno', '0'),
(331, 159, 'Serviços', 0, 'servicos.php', 'modulos/vekttor/servicos', 'abre', '0'),
(332, 527, 'Pacotes', 0, 'pacotes.php', 'modulos/vekttor/pacotes', 'abre', ''),
(333, 527, 'Modelo Contrato Revendedor', 130, 'contrato.php', 'modulos/vekttor/contrato_revendedora', 'abre', ''),
(334, 159, 'Modelo Contrato Cliente', 140, 'contrato.php', 'modulos/vekttor/contrato_cliente', 'abre', '0'),
(335, 159, 'Relatórios', 150, '', '', 'expande', '0'),
(337, 335, 'Analise de Revendedor', 0, 'analise_revendedor.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(338, 335, 'Analise de Mensalidades', 1, 'analise_mensalidades.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(357, 159, 'Tutorial', 160, '', '', 'expande', '0'),
(358, 357, 'Ajuda', 0, 'index.php', 'modulos/vekttor/tutorial', 'abre', '0'),
(341, 335, 'Rank Vendedores', 2, 'rank_vendedores.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(342, 335, 'Venda de pacote', 3, 'venda_pacotes.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(343, 0, 'Revenda Vekttor', 140, 'configuracao.php', 'modulos/revenda_vekttor/configuracao', 'expande', ''),
(344, 343, 'Vendedor', 0, 'vendedor.php', 'modulos/revenda_vekttor/vendedor', 'abre', '0'),
(345, 343, 'Configuração', 0, 'configuracao.php', 'modulos/revenda_vekttor/configuracao', 'abre', '0'),
(346, 343, 'Contato', 0, 'contato.php', 'modulos/revenda_vekttor/contato', 'abre', '0'),
(348, 343, 'Relatórios', 50, '', '', 'expande', '0'),
(349, 348, 'Venda por vendedor', 1, 'venda_vendedor.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(350, 348, 'Vendedor por Atendimento', 2, 'vendedor_atendimento.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(351, 348, 'Vendedor por Fechamento', 3, 'vendedor_fechamento.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(352, 343, 'Atendimento de Vendedor', 40, 'atendimento_vendedor.php', 'modulos/revenda_vekttor/atendimento_vendedor', 'abre', '0'),
(353, 527, 'Revendas', 0, 'revenda.php', 'modulos/revenda_vekttor/revenda', 'abre', ''),
(354, 343, 'Venda', 0, 'venda.php', 'modulos/revenda_vekttor/venda', 'abre', '0'),
(355, 348, 'Venda por Período', 4, 'venda_periodo.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(356, 341, 'Vendas', 1, 'venda_vendedores.php', 'modulos/vekttor/relatorios', 'interno', '0'),
(359, 349, 'Venda por Vendedor Analitico', 0, 'venda_vendedor_analitico.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(360, 350, 'Vendedor por Atendimento Analitico', 0, 'vendedor_atendimento_analitico.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(361, 351, 'Vendedor Por Fechamento Analítico', 0, 'vendedor_fechamento_analitico.php', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(362, 355, 'Venda por Periodo Analitico', 0, 'venda_periodo_analitico', 'modulos/revenda_vekttor/relatorios', 'abre', '0'),
(363, 146, 'Eleitores', 0, 'eleitores_index.php', 'modulos/eleitoral/relatorios', 'abre', '0'),
(408, 410, 'Cadastro de Promocao', 45, 'promocao.php', 'modulos/eleitoral/promocao', 'abre', '0'),
(365, 337, 'Analise Revendedor Analítico', 0, 'analise_revendedor_analitico.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(366, 338, 'Analise de Mensalidades Analítico', 0, 'analise_mensalidade_analitico.php', 'modulos/vekttor/relatorios', 'abre', '0'),
(367, 0, 'Agendamendo', 0, 'agendadiaria.php', 'modulos/agendamento/agenda_diaria/', 'expande', ''),
(368, 0, 'Odonto', 0, 'atendimento.php', 'modulos/odonto/atendimento/', 'expande', ''),
(369, 0, 'E-mail Marketing', 0, 'emailmarketing.php', 'modulos/emailmarketing/emailmarketing', 'expande', ''),
(370, 0, 'SMS', 0, 'odontosms.php', 'modulos/sms/odonto', 'expande', ''),
(371, 380, 'Convenio', 10, 'convenio.php', 'modulos/odonto/convenios', 'abre', '0'),
(372, 367, 'Agenda Diaria', 0, 'agendadiaria.php', 'modulos/agendamento/agenda_diaria/', 'abre', '1'),
(373, 380, 'Procedimentos', 20, 'servicos.php', 'modulos/odonto/servicos', 'abre', '0'),
(374, 380, 'Modelos  de Contrato', 30, 'modelo_contrato.php', 'modulos/odonto/modelo_contrato', 'abre', '0'),
(376, 369, 'E-Mail Marketing', 10, 'emailmarketing.php', 'modulos/emailmarketing/emailmarketing', 'abre', '0'),
(398, 407, 'SMS Importados', 45, 'sms_importado.php', 'modulos/eleitoral/sms_importado/', 'abre', '0'),
(380, 368, 'Cadastros', 40, '', '', 'expande', '0'),
(382, 380, 'Odontologo', 15, 'odontologo.php', 'modulos/odonto/odontologo', 'abre', '0'),
(383, 368, 'Fila de Espera', 10, 'fila_de_espera.php', 'modulos/odonto/fila_espera', 'abre', ''),
(389, 368, 'Relatórios', 60, '', '', 'expande', '0'),
(386, 370, 'Enviar SMS', 0, 'odontosms.php', 'modulos/sms/odonto', 'abre', '0'),
(387, 368, 'Atendimento', 20, 'atendimento.php', 'modulos/odonto/atendimento/', 'abre', ''),
(388, 368, 'Aprovação e Pagamento', 30, 'pagamento.php', 'modulos/odonto/pagamento', 'abre', ''),
(390, 389, 'Atendimento por Odontólogo', 1, 'atendimento_odontologo.php', 'modulos/odonto/relatorios', 'abre', '0'),
(391, 389, 'Última Consulta Cliente', 2, 'ultima_consulta_cliente.php', 'modulos/odonto/relatorios', 'abre', '0'),
(392, 306, 'Atividades Por Colaborador', 50, 'atividade_colaborador.php', 'modulos/ordem_servico/relatorios', 'abre', '0'),
(393, 314, 'Entregas Atrasadas', 30, 'entregas_atrasadas.php', 'modulos/aluguel/relatorios/entregas_atrasadas', 'abre', '0'),
(394, 389, 'Cliente X Serviço X Tempo', 3, 'cliente_servicos_tempo.php', 'modulos/odonto/relatorios/cliente_servico_tempo', 'abre', '0'),
(395, 394, 'Cliente x Tempo', 10, 'cliente_tempo.php', 'modulos/odonto/relatorios/cliente_servico_tempo', 'interno', '0'),
(396, 3, 'Relatorios', 70, '', '', 'expande', ''),
(397, 396, 'Histórico de Produto', 0, 'historico_produto.php', 'modulos/estoque/relatorios', 'abre', '0'),
(399, 204, 'Todas Aulas', 0, 'aulas.php', 'modulos/escolar/aulas', 'abre', '0'),
(400, 407, 'Importação Facebook', 47, 'importacao_facebook.php', 'modulos/eleitoral/importacao_facebook', 'abre', '0'),
(401, 122, 'Importação Rádio', 48, 'importacao_radio.php', 'modulos/eleitoral/importacao_radio', 'abre', '0'),
(402, 122, 'E-mail Marketing', 55, 'emailmarketing.php', 'modulos/eleitoral/emailmarketing', 'abre', '0'),
(403, 224, 'Alunos Reprovados', 85, 'reprovados.php', 'modulos/escolar/alunos_reprovados/', 'abre', '0'),
(404, 271, 'Financeiro', 0, 'financeiro.php', 'modulos/escolar/area_aluno/financeiro', 'abre', '0'),
(405, 146, 'Aniversariante', 0, 'aniversariante.php', 'modulos/eleitoral/aniversariante', 'abre', '0'),
(406, 407, 'Importação E-mail', 49, 'importacao_email.php', 'modulos/eleitoral/importacao_email', 'abre', '0'),
(407, 122, 'Importação', 100, '', '', 'expande', '0'),
(409, 410, 'Participante Promoção', 46, 'participante_promocao.php', 'modulos/eleitoral/participante_promocao', 'abre', '0'),
(410, 122, 'Promoção', 110, 'promocao.php', '', 'expande', '0'),
(411, 402, 'Emails Enviados', 1, 'emails_enviados.php', 'modulos/eleitoral/emailmarketing/', 'interno', '0'),
(412, 402, 'Emails Recebidos', 2, 'emails_recebidos.php', 'modulos/eleitoral/emailmarketing/', 'interno', '0'),
(413, 402, 'Não Enviados', 3, 'emails_naoenviados.php', 'modulos/eleitoral/emailmarketing/', 'interno', '0'),
(414, 376, 'Emails Enviados', 1, 'emails_enviados.php', 'modulos/emailmarketing/emailmarketing/', 'interno', '0'),
(415, 376, 'Recebidos ', 2, 'emails_recebidos.php', 'modulos/emailmarketing/emailmarketing/', 'interno', '0'),
(416, 376, 'Emails Não Recebidos', 3, 'emails_naoenviados.php', 'modulos/emailmarketing/emailmarketing/', 'interno', '0'),
(417, 93, 'Cadastro de Empresa', 10, 'empresa.php', 'modulos/rh/empresa/', 'abre', ''),
(418, 93, 'Movimentacao', 20, '', '', 'expande', '0'),
(419, 418, 'Admissão de Funcionário', 0, 'funcionarios.php', 'modulos/rh/funcionarios', 'abre', '0'),
(420, 419, 'Funcionario', 1, 'lista_funcionario.php', 'modulos/rh/funcionarios', 'interno', '0'),
(421, 93, 'Modelos de Contrato', 50, 'modelo_contrato.php', 'modulos/odonto/modelo_contrato/', 'abre', '0'),
(422, 418, 'Alteração de Salário', 1, 'alteracao_salario.php', 'modulos/rh/alteracao_salario/', 'abre', '0'),
(423, 422, 'Alteração Salário Funcionário', 1, 'alteracao_salario_funcionario.php', 'modulos/rh/alteracao_salario/', 'interno', '0'),
(424, 418, 'Mudança de Cargo', 2, 'mudanca_cargo.php', 'modulos/rh/mudanca_cargo/', 'abre', '0'),
(425, 424, 'Mudança Cargo Funcionario', 1, 'mudanca_cargo_funcionario.php', 'modulos/rh/mudanca_cargo/', 'interno', '0'),
(426, 418, 'Demissão de Funcionário', 3, 'demissao_funcionario.php', 'modulos/rh/demissao_funcionario/', 'abre', '0'),
(427, 426, 'Demissão', 1, 'demissao.php', 'modulos/rh/demissao_funcionario/', 'interno', '0'),
(428, 93, 'Cobrança', 30, '', '', 'expande', '0'),
(429, 428, 'Cobrança', 1, 'cobranca.php', 'modulos/rh/cobranca', 'abre', '0'),
(430, 428, 'Relatório', 2, 'relatorio.php', 'modulos/rh/cobranca', 'abre', '0'),
(431, 430, 'Relatório de Cobranças', 1, 'relatorio_interno.php', 'modulos/rh/cobranca/', 'interno', '0'),
(432, 93, 'Tabelas', 35, '', '', 'expande', '0'),
(433, 432, 'INSS', 1, 'inss.php', 'modulos/rh/tabelas/inss', 'abre', '0'),
(434, 432, 'Salario Familia', 0, 'salario_familia.php', 'modulos/rh/tabelas/salario_familia', 'abre', '0'),
(435, 432, 'IRPF', 3, 'irpf.php', 'modulos/rh/tabelas/irpf', 'abre', '0'),
(436, 418, 'Férias', 36, 'ferias.php', 'modulos/rh/ferias/', 'abre', '0'),
(437, 204, 'Resumo de Matriculas', 1000, 'matriculas.php', 'modulos/escolar/relatorios', 'blank', '0'),
(438, 204, 'Ultimas Matriculas', 2000, 'ultimas_matriculas.php', 'modulos/escolar/relatorios', 'blank', '0'),
(439, 93, 'Folha de Pagamento', 60, 'folha_pagamento.php', 'modulos/rh/folha_pagamento', 'abre', '0'),
(440, 93, 'Hora Extra', 36, 'hora_extra.php', 'modulos/rh/hora_extra/', 'abre', '0'),
(441, 439, 'Gerenciar Folha de Pagamento', 5, 'administracao_folha_pagamento.php', 'modulos/rh/folha_pagamento/', 'interno', '0'),
(442, 440, 'Hora Extra Funcionário', 1, 'hora_extra_funcionario.php', 'modulos/rh/hora_extra/', 'interno', '0'),
(443, 418, 'Relatório de Movimentações', 60, 'relatorio_movimentacoes.php', 'modulos/rh/relatorios/', 'abre', '0'),
(444, 432, 'Feriados', 0, 'feriado.php', 'modulos/rh/tabelas/feriados', 'abre', '0'),
(445, 93, 'Alterar Folha de Pagamento', 70, 'folha_pagamento.php', 'modulos/rh/folha_pagamento/', 'abre', '0'),
(446, 445, 'Alteração de Folha', 5, 'administracao_folha_pagamento.php', 'modulos/rh/folha_pagamento/', 'interno', '0'),
(449, 6, 'Backup Completo', 10, '', 'http://dev.vkt.srv.br/fullbackup.php', 'blank', ''),
(450, 554, 'CAGED', 80, 'caged.php', 'modulos/rh/caged', 'abre', ''),
(452, 275, 'Impressoes OS', 11, 'impressao_os.php', 'modulos/ordem_servico/impressao_os/', 'abre', '0'),
(453, 122, 'Definir Sexo', 0, 'definir_sexo.php', 'modulos/eleitoral/definir_sexo', 'abre', '0'),
(454, 0, 'Escolar2', 0, 'visaogeral.php', 'modulos/escolar2/visao_geral', 'expande', ''),
(455, 454, 'Cadastro', 0, '', '', 'expande', '0'),
(456, 455, 'Estrutura Curricular', 10, 'cursos.php', 'modulos/escolar2/cursos/', 'abre', ''),
(478, 502, 'Lançamento Notas', 0, 'area_professor.php', 'modulos/escolar2/area_professor', 'abre', ''),
(458, 455, 'Escolas', 1, 'escolas.php', 'modulos/escolar2/escolas/', 'abre', ''),
(459, 455, 'Calendário Escolar', 75, 'agendadiaria.php', 'modulos/escolar2/calendario_escolar/', 'abre', ''),
(460, 455, 'Organizar Turmas', 60, 'vagas.php', 'modulos/escolar2/vagas/', 'abre', '0'),
(461, 454, 'Matriculas', 10, '', '', 'expande', '0'),
(462, 461, 'Confirmação de Matrículas', 10, 'matricula_confirmacao.php', 'modulos/escolar2/matricula_confirmacao/', 'abre', '0'),
(502, 454, 'Diário Eletrônico', 30, '', '', 'expande', '0'),
(479, 454, 'Área do Aluno', 60, '', '', 'expande', '0'),
(467, 455, 'Cargos', 15, 'cargos.php', 'modulos/escolar2/cadastros/cargos', 'abre', ''),
(469, 455, 'Funcionários', 20, 'professores.php', 'modulos/escolar2/cadastros/professores', 'abre', ''),
(470, 45, 'Criar Cotação', 2, 'criar_cotacao.php', 'modulos/cozinha/cotacao', 'interno', '0'),
(477, 455, 'Modelo de contrato', 80, 'modelo_contrato.php', 'modulos/odonto/modelo_contrato', 'abre', ''),
(473, 461, 'Matricular Aluno', 0, 'matricula_confirmacao.php', 'modulos/escolar2/matricula_confirmacao', 'abre', '0'),
(474, 460, 'Horários', 50, 'preenchimento_horarios.php', 'modulos/escolar2/cadastros/preenchimento_horarios', 'interno', '0'),
(475, 419, 'Funcionários Aniversariantes', 2, 'funcionarios_aniversariantes.php', 'modulos/rh/funcionarios', 'interno', '0'),
(480, 396, 'Consumo', 2, 'consumo_mensal.php', 'modulos/estoque/relatorios/consumo_mensal', 'abre', '0'),
(481, 396, 'Posição Estoque', 1, 'posicao_estoque.php', 'modulos/estoque/relatorios/posicao_estoque', 'abre', '0'),
(482, 396, 'Ocorrencias', 3, 'ocorrencias.php', 'modulos/estoque/relatorios/ocorrencias', 'abre', '0'),
(483, 478, 'Lista de Aulas E2', 0, 'lista_aula.php', 'modulos/escolar2/area_professor/aula', 'abre', ''),
(484, 455, 'Períodos de Avaliação', 70, 'periodos_avaliacao.php', 'modulos/escolar2/cadastros/periodos_avaliacao', 'abre', '0'),
(485, 554, 'SEFIP', 90, 'sefip_lista.php', 'modulos/rh/sefip', 'abre', ''),
(486, 481, 'Detalhes Posição Estoque', 1, 'detalhes_posicao_estoque.php', 'modulos/estoque/relatorios/posicao_estoque', 'interno', '0'),
(487, 480, 'Detalhes Consumo Mensal', 1, 'detalhes_consumo_mensal.php', 'modulos/estoque/relatorios/consumo_mensal', 'interno', '0'),
(488, 482, 'Detalhes Ocorrencias', 1, 'detalhes_ocorrencias.php', 'modulos/estoque/relatorios/ocorrencias/', 'interno', '0'),
(489, 483, 'Chamada', 0, 'chamada_aluno_aula.php', 'modulos/escolar2/area_professor/aula', 'interno', '0'),
(490, 454, 'Aulas Online', 70, 'aulas_online.php', 'modulos/escolar2/aulas_online_cadastro/', 'abre', '0'),
(491, 490, 'Aulas do Módulo', 0, 'lista_aulas_modulo.php', 'modulos/escolar2/aulas_online_cadastro/aulas_online_cadastradas/', 'interno', '0'),
(492, 491, 'Arquivos da aula', 0, 'arquivos_aula_online.php', 'modulos/escolar2/aulas_online_cadastro/aulas_online_cadastradas/arquivos_aula_online/', 'abre', '0'),
(493, 478, 'Lista Avaliação E2', 0, 'lista_avaliacao.php', 'modulos/escolar2/area_professor/avaliacao', 'interno', '0'),
(494, 493, 'Nota Avaliação', 0, 'nota_aluno_avaliacao.php', 'modulos/escolar2/area_professor/avaliacao', 'interno', '0'),
(495, 478, 'Média', 0, 'lista_alunos.php', 'modulos/escolar2/area_professor/media', 'interno', '0'),
(496, 495, 'Média Final', 0, 'media_final.php', 'modulos/escolar2/area_professor/media', 'interno', '0'),
(497, 503, 'Todas Aulas', 60, 'aulas.php', 'modulos/escolar2/aulas', 'abre', '0'),
(498, 3, 'Consumo', 45, 'consumo.php', 'modulos/estoque/consumo/', 'abre', ''),
(499, 498, 'Novo Consumo', 1, 'novo_consumo.php', 'modulos/estoque/consumo/', 'interno', '0'),
(500, 3, 'Zerar Estoque Unidade', 97, 'zerar_estoque.php', 'modulos/estoque/zerar_estoque', 'abre', '0'),
(501, 396, 'Consumo Grupo Produto', 4, 'consumo_grupo_produto.php', 'modulos/estoque/relatorios/consumo_grupo_produto', 'abre', '0'),
(503, 454, 'Administrar Escolar', 20, '', '', 'expande', '0'),
(504, 503, 'Consulta Aluno', 2, 'alunos.php', 'modulos/escolar2/aluno', 'abre', '0'),
(505, 503, 'Boletim em Massa', 10, 'boletim_massa.php', '', 'abre', '0'),
(506, 503, 'Transferência de Aluno', 20, 'transferencia.php', 'modulos/escolar2/transferencia', 'abre', '0'),
(507, 503, 'Cancelar Matrícula', 5, 'cancelar.php', 'modulos/escolar2/cancelar_matricula', 'abre', '0'),
(508, 503, 'Aniversariantes', 70, 'aniversariante.php', 'modulos/escolar2/aniversariante', 'abre', '0'),
(509, 503, 'Visão Geral', 0, 'visaogeral.php', 'modulos/escolar2/visao_geral', 'abre', '0'),
(510, 501, 'Detalhes Consumo Grupo Produto', 1, 'detalhamento_consumo_grupo_produto.php', 'modulos/estoque/relatorios/consumo_grupo_produto', 'interno', '0'),
(511, 3, 'Configuração', 80, 'configuracao.php', 'modulos/estoque/configuracao', 'abre', ''),
(512, 551, 'Venda Caixa', 45, 'caixa.php', 'modulos/estoque/venda_caixa', 'abre', ''),
(513, 512, 'Caixa', 0, 'nova_venda.php', 'modulos/estoque/venda_caixa/', 'interno', '0'),
(514, 335, 'Último acesso', 0, 'ultimo_acesso.php', 'modulos/vekttor/relatorios/', 'abre', '0'),
(515, 335, 'Quantidade acesso', 0, 'quantidade_acesso.php', 'modulos/vekttor/relatorios/', 'abre', '0'),
(516, 79, 'Fechamento de Caixa', 0, 'fechamento_caixa.php', 'modulos/financeiro/relatorios/venda', 'abre', '0'),
(517, 552, 'Planejamento de Transferência', 65, 'planejamento_transferencia.php', 'modulos/estoque/planejamento_transferencia', 'abre', ''),
(518, 517, 'Itens do Planejamento', 1, 'transferencia_item.php', 'modulos/estoque/planejamento_transferencia', 'interno', '0'),
(519, 368, 'Configuração de relacionamento', 70, 'configuracao_relacionamento.php', 'modulos/odonto/configuracao_relacionamento', 'abre', ''),
(520, 389, 'Convenios X Serviços', 4, 'convenios_servicos.php', 'modulos/odonto/relatorios', 'abre', '0'),
(521, 306, 'Pagamento de OS', 60, 'pagamento.php', 'modulos/ordem_servico/relatorios/pagamentos', 'abre', '0'),
(522, 483, 'Lançar Observações', 1, 'obs_aluno_aula.php', 'modulos/escolar2/area_professor/aula', 'interno', '0'),
(523, 1, 'Dados Cadastrais', 130, 'dados_cadastrais.php', 'modulos/administrativo/dados_cadastrais', 'abre', '0'),
(524, 509, 'Lista Alunos Turma', 1, 'lista_aluno_turma.php', 'modulos/escolar2/visao_geral', 'interno', ''),
(525, 1, 'Dados do Usuário', 140, 'dados_usuario.php', 'modulos/administrativo/dados_usuario', 'abre', '0'),
(526, 89, 'Cadastros', 35, '', '', 'expande', '0'),
(527, 159, 'Administrar Revenda', 149, '', '', 'expande', ''),
(528, 89, 'Painel de atividades', 0, 'tela_producao.php', 'http://vkt.srv.br/~nv/sis/modulos/projetos/atividades/colaborador/', 'blank', ''),
(529, 503, 'Alunos inadimplentes', 90, 'inadimplentes.php', 'modulos/escolar2/inadimplentes', 'abre', ''),
(530, 389, 'Exportar Prontuários', 5, 'exportar_prontuario.php', 'modulos/odonto/atendimento/', 'abre', ''),
(531, 389, 'Atendimento Por Período', 6, 'atendimento_periodo.php', 'modulos/odonto/relatorios/atendimento_periodo', 'abre', ''),
(532, 159, 'Teste', 144, 'teste.php', 'modulos/vekttor/', 'abre', '1'),
(533, 159, 'Avalia ultimos acessos', 145, 'avalia.php', 'modulos/vekttor/avalia/', 'abre', '1'),
(534, 502, 'Lançamento Aulas', 9, 'lancamento.php', 'modulos/escolar2/area_professor/lancamento', 'abre', '1'),
(535, 503, 'Valor Matricula', 3, 'alterar_matricula.php', 'modulos/escolar2/alterar_matricula', 'abre', ''),
(536, 503, 'Livro de Ocorrências', 100, 'livro_ocorrencias.php', 'modulos/escolar2/livro_ocorrencias/', 'abre', ''),
(537, 536, 'Lista Ocorrencias', 1, 'lista_ocorrencias.php', 'modulos/escolar2/livro_ocorrencias', 'interno', ''),
(538, 503, 'Faturamento Por Sala', 110, 'faturamento_sala.php', 'modulos/escolar2/faturamento_sala', 'abre', '1'),
(539, 538, 'Lista Mensalidades Faturamento', 1, 'lista_mensalidades.php', 'modulos/escolar2/faturamento_sala/', 'interno', '1'),
(540, 503, 'Frequência Escolar', 120, 'frequencia_escolar.php', 'modulos/escolar2/frequencia_escolar/', 'abre', '1'),
(541, 503, 'Horários Professor', 65, 'lista_professor.php', 'modulos/escolar2/horarios_professor/', 'abre', ''),
(542, 541, 'Horários', 1, 'horarios_professor.php', 'modulos/escolar2/horarios_professor', 'interno', ''),
(543, 503, 'Relatório Individual', 1, 'relatorio_individual.php', 'modulos/escolar2/administracao/relatorio_individual', 'abre', ''),
(544, 0, 'Cobrança Mensal', 135, 'configuracao.php', 'modulos/cobranca_mensal/configuracao/', 'expande', ''),
(545, 544, 'Clientes e Configurações', 1, 'configuracao.php', 'modulos/cobranca_mensal/configuracao/', 'abre', ''),
(546, 455, 'Grupo de Matérias', 5, 'grupo_materia.php', 'modulos/escolar2/cadastros/grupo_materias', 'abre', ''),
(547, 5, 'Conciliação Bancária', 62, 'conciliacao.php', 'modulos/financeiro/conciliacao', 'abre', ''),
(548, 3, 'Cadastros', 0, '', '', 'expande', ''),
(550, 3, 'Compra', 20, 'compras.php', 'modulos/estoque/compras/', 'expande', ''),
(551, 3, 'Venda', 10, 'caixa.php', 'modulos/estoque/venda_caixa', 'expande', ''),
(552, 3, 'Trasfêrencia de Mercadoria', 30, '', '', 'expande', ''),
(553, 3, 'Beneficiamento', 40, '', '', 'expande', ''),
(554, 93, 'Exportação', 75, '', '', 'expande', ''),
(555, 479, 'Aulas', 20, 'aulas.php', 'modulos/escolar2/area_aluno/aulas', 'abre', ''),
(556, 418, 'Funcionários Em Experiência', 70, 'funcionarios_experiencia.php', 'modulos/rh/relatorios/', 'abre', ''),
(557, 93, 'Solicitação Hora Extra', 37, 'solicitacao_hora_extra.php', 'modulos/rh/solicitacao_hora_extra/', 'abre', ''),
(558, 373, 'Importação Procedimentos', 1, 'importacao_servicos.php', 'modulos/odonto/servicos/', 'interno', '1'),
(559, 159, 'Cadastros Modelo', 170, '', 'modulos/vekttor/cadastros_modelo', 'expande', ''),
(560, 559, 'Plano de Contas', 5, 'plano_de_conta_modelo.php', 'modulos/vekttor/cadastros_modelo/financeiro/plano_de_conta_modelo/', 'abre', ''),
(561, 559, 'Procedimentos Odontológicos', 1, 'servicos.php', 'modulos/odonto/servicos/', 'abre', ''),
(562, 5, 'Importar Plano de Contas', 35, 'importar_plano_de_contas.php', 'modulos/financeiro/importar_plano_de_contas/', 'abre', '1'),
(563, 5, 'Formas de Pagamento', 38, 'formas_de_pagamento.php', 'modulos/financeiro/formas_de_pagamento/', 'abre', ''),
(564, 93, 'Relatórios', 80, '', '', 'expande', ''),
(565, 564, 'Documentos de Funcionários', 1, 'documentos_funcionarios.php', 'modulos/rh/relatorios/', 'abre', ''),
(566, 93, 'Eventos', 100, 'eventos.php', 'modulos/rh/eventos/', 'abre', ''),
(567, 554, 'Planilha CEF', 3, 'cef.php', 'modulos/rh/CEF', 'abre', '');
