modulos/estoque/inventarios/detalhe_inventario/atualiza_inventario.php?
&estoque_inventario_item_id=11916
&nova_qtd=8,52
&qtd_estoque=9
&ocorrencia=
&conversao2=0.52
&unidade=unidade_uso
&qtd_diferenca=0,480
&valor_diferenca=-1,35